In [32]:
import requests as rq
import pandas as pd
import re
from lxml import html

In [270]:
HEADER = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
TXT = '<option selected="" value=""></option><option value="Augsburg">Augsburg</option><option value="Bensheim">Bensheim</option><option value="Berlin">Berlin</option><option value="Berlin-Buch">Berlin-Buch</option><option value="Bochum">Bochum</option><option value="Bonn">Bonn</option><option value="Bottrop">Bottrop</option><option value="Bremen">Bremen</option><option value="Bürstadt">Bürstadt</option><option value="Dortmund">Dortmund</option><option value="Dossenheim">Dossenheim</option><option value="Dresden">Dresden</option><option value="Duisburg">Duisburg</option><option value="Düsseldorf">Düsseldorf</option><option value="Eppelheim">Eppelheim</option><option value="Erfurt">Erfurt</option><option value="Essen">Essen</option><option value="Flensburg">Flensburg</option><option value="Frankfurt">Frankfurt</option><option value="Garching">Garching</option><option value="Gelsenkirchen">Gelsenkirchen</option><option value="Gießen">Gießen</option><option value="Gütersloh">Gütersloh</option><option value="Hamburg">Hamburg</option><option value="Hamm">Hamm</option><option value="Heddesheim">Heddesheim</option><option value="Heidelberg">Heidelberg</option><option value="Heppenheim">Heppenheim</option><option value="Herne">Herne</option><option value="Hockenheim">Hockenheim</option><option value="Kaiserslautern">Kaiserslautern</option><option value="Karlsruhe">Karlsruhe</option><option value="Kassel">Kassel</option><option value="Köln">Köln</option><option value="Ladenburg">Ladenburg</option><option value="Lahr">Lahr</option><option value="Lampertheim">Lampertheim</option><option value="Leipzig">Leipzig</option><option value="Leverkusen">Leverkusen</option><option value="Lippstadt">Lippstadt</option><option value="Ludwigshafen">Ludwigshafen</option><option value="Mannheim">Mannheim</option><option value="Marburg">Marburg</option><option value="Mönchengladbach">Mönchengladbach</option><option value="Mülheim a.d.R.">Mülheim a.d.R.</option><option value="München">München</option><option value="Norderstedt">Norderstedt</option><option value="Nürnberg">Nürnberg</option><option value="Oberhausen">Oberhausen</option><option value="Offenbach am Main">Offenbach am Main</option><option value="Offenburg">Offenburg</option><option value="Potsdam">Potsdam</option><option value="Quickborn">Quickborn</option><option value="Rüsselsheim am Main">Rüsselsheim am Main</option><option value="Schwalbach am Taunus">Schwalbach am Taunus</option><option value="Schwetzingen">Schwetzingen</option><option value="Speyer">Speyer</option><option value="Tübingen">Tübingen</option><option value="Usedom">Usedom</option><option value="Walldorf">Walldorf</option><option value="Weinheim">Weinheim</option><option value="Wiesbaden">Wiesbaden</option><option value="Worms">Worms</option><option value="Würzburg">Würzburg</option>"'

In [266]:
def get_tree(city):
    url = str("http://de.wikipedia.org/wiki/" + str(city))
    return get_city(url)

def get_number(alist, name):
    #idx = alist.index(name)
    indices = [i for i, s in enumerate(alist) if name in s]
    try:
        idx = indices[0]
    except IndexError:
        return 0
    found = False
    while not found:
        idx+=1
        try:
            found, res = match_inhabs(alist[idx].strip(" "))
        except IndexError:
            return 0
    return res


def match_inhabs(s):
    match = re.findall(r"\d", s)
    try:
        result = int("".join(match))
        return True, result
    except:
        return False, 0

    
def get_table_list(tree, rx="//tr//text()"):
    aa = tree.xpath(rx)
    return aa


def aq_pop(city):
    tree = get_tree(city)
    alist = get_table_list(tree)
    return get_number(alist, "Einwohner")


def aquire_data(city, name):
    tree = get_tree(city)
    alist = get_table_list(tree)
    num = get_number(alist, name)
    return num

In [210]:
def get_cities(txt):
    match = re.findall(r"[A-Z]\w+", txt)
    result = list(set(match))
    result.sort()
    return result

In [244]:
def get_city(url):
    r = rq.get(url, headers=HEADER)
    text = r.text
    # print(text)
    #url_string = bytes(r.text, 'iso-8859-1').decode('utf-8')
    tree = html.document_fromstring(r.text)
    return tree

In [271]:
c = get_cities(TXT)

In [272]:
nb = pd.DataFrame({"city": c})

In [273]:
nb["population"] = nb.apply(lambda x: aquire_data(x.city, "Einwohner"), axis=1)

In [274]:
nb["density"] = nb.apply(lambda x: aquire_data(x.city, "Bevölkerungsdichte"), axis=1)

In [275]:
nb = nb[(nb != 0).all(1)]

In [276]:
nb

               city  population  density
0          Augsburg      292851     1994
1          Bensheim       40326      697
2            Berlin     3613495     4052
3            Bochum      365529     2509
4              Bonn      325490     2307
5           Bottrop      117364     1166
6            Bremen      568006     1745
8          Bürstadt       16315      473
9          Dortmund      586600     2090
10       Dossenheim       12477      881
11          Dresden      551072     1678
12         Duisburg      498110     2140
13       Düsseldorf      617280     2839
14        Eppelheim       15250     2675
15           Erfurt      212988      789
16            Essen      583393     2774
17        Flensburg       88519     1560
20    Gelsenkirchen      260305     2480
21           Gießen       87343     1204
22        Gütersloh       99315      887
23          Hamburg       25242     2430
24             Hamm      179185      791
25       Heddesheim       11464      779
26       Heidelberg      160601     1476
27       Heppenheim       25755      494
28            Herne      156490     3043
29       Hockenheim       21739      624
30   Kaiserslautern       99684      713
31        Karlsruhe      311919     1798
32           Kassel      200736     1880
33             Köln     1080394     2668
34        Ladenburg       11532      607
35             Lahr       46156      661
36      Lampertheim       32609      451
37          Leipzig      581980     1954
38       Leverkusen      163577     2074
39        Lippstadt       67936      598
40     Ludwigshafen      168497     2173
42         Mannheim      307997     2125
43          Marburg       76226      615
44  Mönchengladbach      262188     1538
46          München     1456039     4686
47      Norderstedt       78679     1354
48         Nürnberg      515201     2764
49       Oberhausen      211422     2743
51        Offenburg       59060      754
52          Potsdam      175710      932
53        Quickborn       21056      488
54      Rüsselsheim       64922     1114
56     Schwetzingen       21546      996
57           Speyer       50931     1196
59         Tübingen       89447      827
62         Weinheim       45114      776
63        Wiesbaden      278654     1366
64            Worms       83081      764
65         Würzburg      126635     1445

In [277]:
#aquire_data("Augsburg", "Bevölkerungsdichte")

In [278]:
nb.to_csv("nb.csv", index=False)